export const zoneArray = [
  "Asia/Shanghai",
  "America/New_York",
  "America/Chicago",
  "America/Denver",
  "America/Los_Angeles",
  "Europe/London",
  "Asia/Tokyo",
  "Asia/Seoul",
  "America/Mexico_City",
  "Europe/Bucharest",
  "Asia/Ho_Chi_Minh",
  "America/Santiago",
  "America/Port_of_Spain",
  "Europe/Madrid",
  "Australia/Sydney",
  "Africa/Cairo",
  "Africa/Casablanca",
  "Africa/Harare",
  "Africa/Johannesburg",
  "Africa/Lagos",
  "Africa/Monrovia",
  "Africa/Nairobi",
  "America/Argentina/Buenos_Aires",
  "America/Bogota",
  "America/Caracas",
  "America/Chihuahua",
  "America/Godthab",
  "America/La_Paz",
  "America/Lima",
  "America/Managua",
  "America/Mazatlan",
  "America/Monterrey",
  "America/Noronha",
  "America/Sao_Paulo",
  "America/Tijuana",
  "Asia/Almaty",
  "Asia/Baghdad",
  "Asia/Baku",
  "Asia/Bangkok",
  "Asia/Calcutta",
  "Asia/Chongqing",
  "Asia/Dhaka",
  "Asia/Hong_Kong",
  "Asia/Irkutsk",
  "Asia/Jakarta",
  "Asia/Jerusalem",
  "Asia/Kabul",
  "Asia/Kamchatka",
  "Asia/Karachi",
  "Asia/Katmandu",
  "Asia/Kolkata",
  "Asia/Krasnoyarsk",
  "Asia/Kuala_Lumpur",
  "Asia/Kuwait",
  "Asia/Magadan",
  "Asia/Muscat",
  "Asia/Novosibirsk",
  "Asia/Rangoon",
  "Asia/Riyadh",
  "Asia/Singapore",
  "Asia/Taipei",
  "Asia/Tashkent",
  "Asia/Tbilisi",
  "Asia/Tehran",
  "Asia/Ulan_Bator",
  "Asia/Urumqi",
  "Asia/Vladivostok",
  "Asia/Yakutsk",
  "Asia/Yekaterinburg",
  "Asia/Yerevan",
  "Atlantic/Azores",
  "Atlantic/Cape_Verde",
  "Australia/Adelaide",
  "Australia/Brisbane",
  "Australia/Canberra",
  "Australia/Darwin",
  "Australia/Hobart",
  "Australia/Melbourne",
  "Australia/Perth",
  "Canada/Atlantic",
  "Canada/Newfoundland",
  "Canada/Saskatchewan",
  "Etc/Greenwich",
  "Europe/Amsterdam",
  "Europe/Athens",
  "Europe/Belgrade",
  "Europe/Berlin",
  "Europe/Bratislava",
  "Europe/Brussels",
  "Europe/Budapest",
  "Europe/Copenhagen",
  "Europe/Helsinki",
  "Europe/Istanbul",
  "Europe/Lisbon",
  "Europe/Ljubljana",
  "Europe/Minsk",
  "Europe/Moscow",
  "Europe/Paris",
  "Europe/Prague",
  "Europe/Riga",
  "Europe/Rome",
  "Europe/Sarajevo",
  "Europe/Skopje",
  "Europe/Sofia",
  "Europe/Stockholm",
  "Europe/Tallinn",
  "Europe/Vienna",
  "Europe/Vilnius",
  "Europe/Volgograd",
  "Europe/Warsaw",
  "Europe/Zagreb",
  "Pacific/Auckland",
  "Pacific/Fiji",
  "Pacific/Guam",
  "Pacific/Honolulu",
  "Pacific/Kwajalein",
  "Pacific/Midway",
  "Pacific/Port_Moresby",
  "Pacific/Samoa",
  "Pacific/Tongatapu",
  "US/Alaska",
  "US/Arizona",
  "US/Central",
  "US/East-Indiana",
  "US/Eastern",
  "US/Mountain",
  "UTC",
  "America/Toronto",
  "America/Adak",
  "America/Anchorage",
  "America/Anguilla",
  "America/Antigua",
  "America/Araguaina",
  "America/Argentina/Catamarca",
  "America/Argentina/Cordoba",
  "America/Argentina/Jujuy",
  "America/Argentina/La_Rioja",
  "America/Argentina/Mendoza",
  "America/Argentina/Rio_Gallegos",
  "America/Argentina/Salta",
  "America/Argentina/San_Juan",
  "America/Argentina/San_Luis",
  "America/Argentina/Tucuman",
  "America/Argentina/Ushuaia",
  "America/Aruba",
  "America/Asuncion",
  "America/Atikokan",
  "America/Bahia",
  "America/Bahia_Banderas",
  "America/Barbados",
  "America/Belem",
  "America/Belize",
  "America/Blanc-Sablon",
  "America/Boa_Vista",
  "America/Boise",
  "America/Cambridge_Bay",
  "America/Campo_Grande",
  "America/Cancun",
  "America/Cayenne",
  "America/Cayman",
  "America/Costa_Rica",
  "America/Creston",
  "America/Cuiaba",
  "America/Curacao",
  "America/Danmarkshavn",
  "America/Dawson",
  "America/Dawson_Creek",
  "America/Detroit",
  "America/Dominica",
  "America/Edmonton",
  "America/Eirunepe",
  "America/El_Salvador",
  "America/Fort_Nelson",
  "America/Fortaleza",
  "America/Glace_Bay",
  "America/Goose_Bay",
  "America/Grand_Turk",
  "America/Grenada",
  "America/Guadeloupe",
  "America/Guatemala",
  "America/Guayaquil",
  "America/Guyana",
  "America/Halifax",
  "America/Havana",
  "America/Hermosillo",
  "America/Indiana/Indianapolis",
  "America/Indiana/Knox",
  "America/Indiana/Marengo",
  "America/Indiana/Petersburg",
  "America/Indiana/Tell_City",
  "America/Indiana/Vevay",
  "America/Indiana/Vincennes",
  "America/Indiana/Winamac",
  "America/Inuvik",
  "America/Iqaluit",
  "America/Jamaica",
  "America/Juneau",
  "America/Kentucky/Louisville",
  "America/Kentucky/Monticello",
  "America/Kralendijk",
  "America/Lower_Princes",
  "America/Maceio",
  "America/Manaus",
  "America/Marigot",
  "America/Martinique",
  "America/Matamoros",
  "America/Menominee",
  "America/Merida",
  "America/Metlakatla",
  "America/Miquelon",
  "America/Moncton",
  "America/Montevideo",
  "America/Montserrat",
  "America/Nassau",
  "America/Nipigon",
  "America/Nome",
  "America/North_Dakota/Beulah",
  "America/North_Dakota/Center",
  "America/North_Dakota/New_Salem",
  "America/Ojinaga",
  "America/Panama",
  "America/Pangnirtung",
  "America/Paramaribo",
  "America/Phoenix",
  "America/Port-au-Prince",
  "America/Porto_Velho",
  "America/Puerto_Rico",
  "America/Punta_Arenas",
  "America/Rainy_River",
  "America/Rankin_Inlet",
  "America/Recife",
  "America/Regina",
  "America/Resolute",
  "America/Rio_Branco",
  "America/Santarem",
  "America/Santo_Domingo",
  "America/Scoresbysund",
  "America/Sitka",
  "America/St_Barthelemy",
  "America/St_Johns",
  "America/St_Kitts",
  "America/St_Lucia",
  "America/St_Thomas",
  "America/St_Vincent",
  "America/Swift_Current",
  "America/Tegucigalpa",
  "America/Thule",
  "America/Thunder_Bay",
  "America/Tortola",
  "America/Vancouver",
  "America/Whitehorse",
  "America/Winnipeg",
  "America/Yakutat",
  "America/Yellowknife",
  "Europe/Andorra",
  "Europe/Astrakhan",
  "Europe/Busingen",
  "Europe/Chisinau",
  "Europe/Dublin",
  "Europe/Gibraltar",
  "Europe/Guernsey",
  "Europe/Isle_of_Man",
  "Europe/Jersey",
  "Europe/Kaliningrad",
  "Europe/Kiev",
  "Europe/Kirov",
  "Europe/Luxembourg",
  "Europe/Malta",
  "Europe/Mariehamn",
  "Europe/Monaco",
  "Europe/Oslo",
  "Europe/Podgorica",
  "Europe/Samara",
  "Europe/San_Marino",
  "Europe/Saratov",
  "Europe/Simferopol",
  "Europe/Tirane",
  "Europe/Ulyanovsk",
  "Europe/Uzhgorod",
  "Europe/Vaduz",
  "Europe/Vatican",
  "Europe/Zaporozhye",
  "Europe/Zurich",
  "Asia/Aden",
  "Asia/Amman",
  "Asia/Anadyr",
  "Asia/Aqtau",
  "Asia/Aqtobe",
  "Asia/Ashgabat",
  "Asia/Atyrau",
  "Asia/Bahrain",
  "Asia/Barnaul",
  "Asia/Beirut",
  "Asia/Bishkek",
  "Asia/Brunei",
  "Asia/Chita",
  "Asia/Choibalsan",
  "Asia/Colombo",
  "Asia/Damascus",
  "Asia/Dili",
  "Asia/Dubai",
  "Asia/Dushanbe",
  "Asia/Famagusta",
  "Asia/Gaza",
  "Asia/Hebron",
  "Asia/Hovd",
  "Asia/Jayapura",
  "Asia/Kathmandu",
  "Asia/Khandyga",
  "Asia/Kuching",
  "Asia/Macau",
  "Asia/Makassar",
  "Asia/Manila",
  "Asia/Nicosia",
  "Asia/Novokuznetsk",
  "Asia/Omsk",
  "Asia/Oral",
  "Asia/Phnom_Penh",
  "Asia/Pontianak",
  "Asia/Pyongyang",
  "Asia/Qatar",
  "Asia/Qyzylorda",
  "Asia/Sakhalin",
  "Asia/Samarkand",
  "Asia/Srednekolymsk",
  "Asia/Thimphu",
  "Asia/Tomsk",
  "Asia/Ulaanbaatar",
  "Asia/Ust-Nera",
  "Asia/Vientiane",
  "Asia/Yangon",
  "Australia/Broken_Hill",
  "Australia/Currie",
  "Australia/Eucla",
  "Australia/Lindeman",
  "Australia/Lord_Howe",
  "Pacific/Apia",
  "Pacific/Bougainville",
  "Pacific/Chatham",
  "Pacific/Chuuk",
  "Pacific/Easter",
  "Pacific/Efate",
  "Pacific/Enderbury",
  "Pacific/Fakaofo",
  "Pacific/Funafuti",
  "Pacific/Galapagos",
  "Pacific/Gambier",
  "Pacific/Guadalcanal",
  "Pacific/Kiritimati",
  "Pacific/Kosrae",
  "Pacific/Majuro",
  "Pacific/Marquesas",
  "Pacific/Nauru",
  "Pacific/Niue",
  "Pacific/Norfolk",
  "Pacific/Noumea",
  "Pacific/Pago_Pago",
  "Pacific/Palau",
  "Pacific/Pitcairn",
  "Pacific/Pohnpei",
  "Pacific/Rarotonga",
  "Pacific/Saipan",
  "Pacific/Tahiti",
  "Pacific/Tarawa",
  "Pacific/Wake",
  "Pacific/Wallis"
]

export const ReportTypeEnum = {
  OfficialCourseReport: 1
}

export const CourseTypeEnum = {
  OfficialCourse: 1,
  DemoCourse: 0
}

export const NewFeedbackStartTime: number = 1515974400

export const LogLevel = {
  Warning: 2,
  Error: 1
}

export const NetworkConditionErrors: { [key: string]: string } = {
  "1": "一般性的错误 (没有明确归类的错误原因)",
  "2": "API 调用了无效的参数,例如指定的频道名含有非法字符",
  "3":
    "SDK 的模块没有准备好，例如某个 API 调用依赖于某个模块，但该模块尚未准备提供服务",
  "4": "SDK 不支持该功能",
  "5": "调用被拒绝,仅供 SDK 内部使用，不通过 API 或者回调事件返回给应用程序",
  "6": "传入的缓冲区大小不足以存放返回的数据",
  "7": "SDK 尚未初始化，就调用其 API",
  "9": "没有操作权限,仅供 SDK 内部使用，不通过 API 或者回调事件返回给应用程序",
  "10":
    "API 调用超时,有些 API 调用需要 SDK 返回结果，如果 SDK 处理时间过长，会出现此错误",
  "11": "请求被取消,仅供 SDK 内部使用，不通过 API 或者回调事件返回给应用程序",
  "12": "调用频率太高,仅供 SDK 内部使用，不通过 API 或者回调事件返回给应用程序",
  "13":
    "SDK 内部绑定到网络 socket 失败,仅供 SDK 内部使用，不通过 API 或者回调事件返回给应用程序",
  "14": "网络不可用,仅供 SDK 内部使用，不通过 API 或者回调事件返回给应用程序",
  "15":
    "没有网络缓冲区可用,仅供 SDK 内部使用，不通过 API 或者回调事件返回给应用程序",
  "17":
    "加入频道被拒绝,一般是因为用户已进入频道，再次调用加入频道的 API，例如 joinChannel，会返回此错误",
  "18":
    "离开频道失败,一般是因为用户已离开某频道，再次调用退出频道的 API，例如 leaveChannel，会返回此错误",
  "19": "资源已被占用，不能重复使用",
  "20":
    "SDK 放弃请求，可能由于请求次数太多,仅供 SDK 内部使用，不通过 API 或者回调事件返回给应用程序",
  "21": "Windows 下特定的防火墙设置导致 SDK 初始化失败然后崩溃",
  "101": "指定的 App ID 无效",
  "102": "指定的频道名无效",
  "103": "无可用频道",
  "104": "加入频道超时",
  "105": "拒绝加入频道",
  "109": "当前使用的 TOKEN 过期，不再有效",
  "110": "指定的 TOKEN 无效,一般是因为密钥生成的不对",
  "113": "用户不在频道内",
  "114": "数据太大",
  "115": "码率受限",
  "116": "数据流/通道过多",
  "117": "数据流发送超时",
  "1001": "加载媒体引擎失败",
  "1002": "启动媒体引擎开始通话失败",
  "1003": "启动摄像头失败",
  "1004": "启动视频渲染模块失败",
  "1005": "音频设备模块出现一般性错误（没有明显归类的错误）",
  "1006": "音频设备模块: 使用 java 资源出现错误",
  "1007": "音频设备模块: 设置的采样频率出现错误",
  "1008": "音频设备模块: 初始化播放设备出现错误",
  "1009": "音频设备模块: 启动播放设备出现错误",
  "1010": "音频设备模块: 停止播放设备出现错误",
  "1011": "音频设备模块: 初始化录音设备时出现错误",
  "1012": "音频设备模块: 启动录音设备出现错误",
  "1013": "音频设备模块: 停止录音设备出现错误",
  "1015": "音频设备模块: 运行时播放出现错误",
  "1017": "音频设备模块: 运行时录音错误",
  "1018": "音频设备模块: 录音失败",
  "1022": "音频设备模块: 初始化 loopback 设备错误",
  "1023": "音频设备模块: 启动 loopback 设备错误",
  "1501": "视频设备模块: 摄像头没有使用权限",
  "1111": "录音启动失败"
}

export const NetworkConditionWarnings: { [key: string]: string } = {
  "8":
    "指定的 view 无效，使用视频功能时需要指定 view，如果 view 尚未指定，则返回该警告",
  "16": "初始化视频功能失败",
  "20": "请求处于待定状态一般是由于某个模块还没准备好，请求被延迟处理",
  "103": "没有可用的频道资源,可能是因为服务端没法分配频道资源",
  "104":
    "查找频道超时,在加入频道时 SDK 先要查找指定的频道，出现该警告一般是因为网络太差，连接不到服务器",
  "105":
    "查找频道请求被服务器拒绝,服务器可能没有办法处理这个请求或请求是非法的",
  "106":
    "打开频道超时,查找到指定频道后，SDK 接着打开该频道，超时一般是因为网络太差，连接不到服务器",
  "107":
    "打开频道请求被服务器拒绝,服务器可能没有办法处理该请求或该请求是非法的",
  "1014": "音频设备模块: 运行时播放设备出现警告",
  "1016": "音频设备模块: 运行时录音设备出现警告",
  "1019": "音频设备模块: 没有采集到有效的声音数据",
  "1020": "音频设备模块: 播放设备出现故障",
  "1021": "音频设备模块: 录制设备出现故障",
  "1051": "音频设备模块：检测到啸叫",
  "1032": "播放音量过小"
}

export const NetworkPieCategory: { [key: string]: string } = {
  "0": "未知异常",
  "1": "很差",
  "2": "较差",
  "3": "一般",
  "4": "好"
}
